itclub_site/itclub_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from itclub import views
from itclub_site import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('itclub.urls')),
    path('users/', include('users.urls', namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
    # если в '' вписать префикс (напр. 'itclub/'), то он будет подставляться перед адресами в itclub.urls,
    #     т.е. станет '/itclub/'  и '/itclub/groups/' соответственно.
]

if settings.DEBUG:  # необходимо только в режиме отладки
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404=views.page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Статьи учеников ITclub"

itclub_site/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('password-change/', PasswordChangeView.as_view(), name='password_change'), Вариант со стандартной формой смены пароля
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name='password_change_done'
         ),

    # для т.ч. увидеть форму сбросв пароля
    path('password-reset/',
         PasswordResetView.as_view(template_name="users/password_reset_form.html",
                                   email_template_name="users/password_reset_email.html",
                                   success_url=reverse_lazy("users:password_reset_done")
                                   ),
         name='password_reset'
         ),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'
         ),


    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy("users:password_reset_complete")
                                          ),
         name='password_reset_confirm'
         ),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'
         ),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

itclub_site/templates/base.html
{% load static %}
{% load itclub_tags %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'itclub/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'itclub/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
				<li class="logo"><a href="{% url 'home' %}"><img src="{% static 'itclub/images/logo.png' %}" id='img-logo' alt="logo"></a></li>
				{% for m in mainmenu %}
					<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
				{% endfor %}
				{% if user.is_authenticated %}
					<li class="last"><a href="{% url 'users:profile' %}">{{user.username}}</a> | <a href="{% url 'users:logout' %}">Выйти</a></li>
				{% else %}
					<li class="last"><a href="{% url 'users:login' %}">Войти</a> | <a href="{% url 'users:register' %}">Регистрация</a></li>
				{% endif %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		{% if cat_selected == 0 %}
			   <li class="selected">Все года</li>
		{% else %}
			   <li><a href="{% url 'home' %}">Все года</a></li>
		{% endif %}
		{% show_categories cat_selected %}
		<li class="share">
		<p>Наш канал</p>
		<a class="share-yt" href="https://www.youtube.com/" target="_blank" rel="nofollow"></a>
		</li>
		<li>{% show_all_tags %}</li>
	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

{% block navigation %}
{% endblock %}

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2023 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах разрешено со ссылкой на источник.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>